[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["node-fetch"]

[functions."sendTrending"]
  schedule = "0 */3 * * *"

[functions."sendPostNotification"]
  included_files = ["netlify/functions/sendPostNotification.js"]